### PR TITLE
WIP Feature: Select Character Type for pozyx tags

### PR DESCRIPTION
**Pull request by benloh**
Addresses #760 

# Features

screenshot_1336

* Pozyx tags are now listed in the "CHARACTER CONTROLLERS" panel on Main.
* FakeTrack and PTrack controllers are also listed.
* Any input source (pozyx, faketrack, ptrack) can select a new character blueprint at any time.
* When the blueprint is changed, a new agent is created and the old one is removed.  So any state that the agent had is lost.

* If none of the scripts have set controllable inputs (e.g. no blueprints have `isPozyxControllable` or `isPTrackControllable` set to true), the "CHARACTER CONTROLLERS" panel on Main will select the first blueprint by default and issue a warning on the dev console.  This is to prevent the app from crashing.

* FakeTrack functionality has been restored.  Transforms weren't properly calculated for faketrack inputs, so nothing was working.  98f01b96c9d8df209253e819f39ce7bbff615aca adds support that defaults to a faketrack transform (e.g. no transform) so that faketrack entities can be displayed and controlled/moved again.

## To Test/Implement

Test Mapping

1. Make sure one blueprint has `# TAG isPozyxControllable true` set to `true`.  This will be the default blueprint that any new tag is set to.  (You can set more than one `isPozyxControllable`.  If there is more than one, one of the `isPozyxControllable` blueprints will be picked at random.)
2. Start Main
3. Move some pozyx tags around (or use the pozyx Gateway simulator to generate some fake tags).
4. A list of active tags will show in the "CHARACTER CONTROLLERS" area.
5. The active tags will default to the first `isPozyxControllable` blueprint.
6. FakeTrack inputs will default to the first blueprint, since it ignores `isPozyxControllable`.
7. Select any other blueprint from the popup menu for each tag to select a new blueprint type.
8. The old agent will be removed and a new agent created in its place.
9. The old agent state will be lost -- data is not ported from the old blueprint instance to the new blueprint instance.

Test "No Controllable Tag" Tracking

1. Set `isPozyxControllable` and `isPTrackControllable` for all blueprints to false.
2. Run the simulation.
3. The console should not generate any errors
4. Pozyx and PTrack inputs should use a random default blueprint -- this will be randomly selected
5. FakeTrack inputs should default to the first blueprint on the list .

## Caveats

* The list of "CHARACTER CONTROLLERS" on the map will show Character Controllers with their controller ID, but not the selected blueprint name. That information is not currently easily accessed.  It should be possible to address this in future work.  

---

# Technical Background

During each sim loop, inputs coming from PTrack, Pozyx, Character Controllers, and FakeTrack are mapped to agent instance definitions and agents are then created.  We tap into that flow by introducing a way to dynamically select a new agent instance from the list of available agents.  The process is something like this (see the [input to agent flow](https://whimsical.com/input-to-agent-flow-XjPthAzmLFR381wX1RiUuo) whimsical diagram):

1. pozyx tags are updated with inputs.  
6. We detect when a new tag has been added.  When a tag is added, we update a new `instances` state group called `tags` that lists all of the available PTrack, Pozyx, and FakeTrack inputs and their corresponding blueprint names.
7. Those `tags` are listed on the "CHARACTER CONTROLLERS" panel on Main, along with a menu selector for all of the blueprint types that are available.
8. By default, pozyx tags use the default blueprint specified with a `isPozyxControllable` tag.
10. When a tag is selected on the "CHARACTER CONTROLLERS" panel on Main, we update the `tags` group of the `instances` state with a new blueprint id.
11. During the regular simloop update in `dc-inputs`, we add or change the agent definitions using the `tags` table.
12. Later during the `sim-inputs` phase, the agent definitions are mapped to agent instances, either updating or adding a new agent as necessary.  The old agent is removed, and a new agent is created.  State is not maintained across the two agents.

NOTE: WIth this system, ANY blueprint can be controlled by a pozyx tag.  The `# TAG isPozyxControllable` tag is not necessary to make it controllable.  The corollary to this is that we are not excluding any blueprints either.  If exclusion is necessary, we'll need to add a filter to do that.

---

## TO DO
* [x] Not all code has been pushed to the repo yet.
* [x] Crashes if no blueprint has`isPozyxControllable` set to true.
* [x] Test with working pozyx system and working simulation to make sure agent GEMSCRIPTS are working properly
* [x] List only pozyxControllable tags
* [x] predator faketrack error
* [x] character name split
* [x] tags need to be updated after saving map

### CODE REVIEW

**Comment by benloh** [comment]
@jdanish Here's a first pass at selecting character types.  I'm still doing QA and documentation, but I think it basically works.  Please give `dev-bl/character-type` a whirl to see if this does what you want.

**Comment by jdanish** [comment]
In wetlands_beaver_building, the dropdown list includes all characters (not just pozyx enabled ones) and when I switch to predator using fake track, it generates this error and pops back to beaver.

Screenshot 2023-10-04 at 8 38 55 PM

**Comment by benloh** [comment]
Ah. I had implemented it so that ANY blueprint could be selected. I'll add in the filter.

The predator bug looks odd.  But I'll take a look.

**Comment by benloh** [comment]
@jdanish regarding the character name split issue, because the character names and the tag ids are potentially quite long, and we don't really want to make the stage area any smaller, the only solution is to truncate or make the tag or character name shorter.  I don't want to reduce the size of the font too much or it will be hard to read on screen.  Are you OK with truncating the name?  Or do you want to increase the width of the left sidebar?  We can probably get away with reducing the right sidebar.

**Comment by jdanish** [comment]
I’m ok with truncating the name. Thanks!----(from my iPhone)Joshua Danishhttp://www.joshuadanish.comOn Oct 4, 2023, at 11:54 PM, benloh ***@***.***> wrote:﻿
@jdanish regarding the character name split issue, because the character names and the tag ids are potentially quite long, and we don't really want to make the stage area any smaller, the only solution is to truncate or make the tag or character name shorter.  I don't want to reduce the size of the font too much or it will be hard to read on screen.  Are you OK with truncating the name?  Or do you want to increase the width of the left sidebar?  We can probably get away with reducing the right sidebar.

**Comment by jdanish** [comment]
Gabby reports that this mostly works well. However, if you click setup to change the map, and then save, the character controller characters do not reappear unless you reload the screen. I have a video from her if you need, but I think that's clear?

**Comment by benloh** [comment]
All currently reported issues should be addressed:
* Crashes if no blueprint hasisPozyxControllable set to true.
*  List only pozyxControllable tags
*  predator faketrack error
*  character name split
*  tags need to be updated after saving map

**Review by jdanish — APPROVED** [review]

**Comment by benloh** [comment]
One addition note for the record:

Errors coming from dynamically switching a tag's blueprints touch the following features:
* costume
* graphing
* movement
* physics
* touches
* vision
So please watch for errors related to features being switched on and off as you switch blueprints.

**Pull request merged**
