### PR TITLE
Feature: Edit Instance Init Scripts using Wizard

### PR DESCRIPTION
**Pull request by benloh**
Addresses #754

Instance init scripts in the Map Editor were originally edited directly with a code editor.  This adds the ability to edit instance init scripts in a Script Editor window, supporting both a wizard view and a code editor view.

# To Test

1. Open Main
2. Click on "SETUP" to edit the Map
3. Click on an instance in "CHARACTERS" (or if you haven't created an instance already, select blueprint from "ADD CHARACTERS")
4. Click on the instance to expand the Edit view.
5. Click on the "Edit" button to open the init script in a new wizard. 
6. Edit the script using a wizard as you normally would.
7. Click "Save Line" to save changes to the line.
8. Click "Save to Server" to update the init script.
9. The instance will be updated.

Other things to test:
* Delete the init script from Map Editor -- does anything break?
* Delete the init script from Script Editor -- does anything break?
* Drag and drop the instance in the Map Editor view -- are you able to update the position?  If the ScriptEditor window is open while you're dragging, does the code update?
* Make sure default initScript position code works with variations of `prop x setTo...` `prop agent.x setTo..` and `prop character.x setTo..`
* 

# Technical Background

Editing init script is a bit tricky because the wizard needs to pre-compile the blueprint in order to know how to scaffold the wizard editor. The blueprint script needs to be compiled and bundled so that the wizard knows which props and features have been defined and are therefore available to be called in the initScript.  We do this by adding initScripts to the blueprint bundle, and then re-purposing the ScriptEditor components to handle either regular blueprint scripts or just init scripts.

# To Do
* [X] ScriptEditor should indicate whether we're in "Character" edit mode or "Instance" edit mode?  How do we designate the difference since "instance" is not in the vocabulary?  Use "Character Type Editor" vs "Character Instance Editor"?  
* [X] Remove project name from ScriptEditor window
* [x] Use `<bpname>.x`for updating drag init scripts.
* [X] "Save to Server" is not clearing 'isDirty' flag
* [X] After Save Script to Server, character is not updated (alpha change is not reflected)
* [X] If ScriptEditor is open and the user drags, the code should update?  ~~Or do we lock out the drag?~~ We need to update otherwise the user will be left with an out of date ScriptEditor.
* [X] If initScript is deleted from MapEditor while ScriptEditor is open, close the window, don't revert to Blueprint edit view.
* [X] If initScript is deleted from MapEditor while ScriptEditor is open, line selection is broken.  Can we close the window?  Or at least properly revert, removing the initScript? => Window is now closed.
* [X] Changed bp name remains listed in "CHARACTER TYPE SCRIPTS"
* [X] "Children with the same key" error when editing alpha -- CAN'T REPLICATE or FIXED.  Won't do.
* [X] Bookmarks menu needs to be added if a bookmarkable comment is added. -- Fixed by 00a4022d9d4e5b4cc9aa65bd2a3828c1b2249aae

### CODE REVIEW

**Comment by jdanish** [comment]
_If ScriptEditor is open and the user drags, the code should update? Or do we lock out the drag?_
Ideally update, but if it is a hassle that's fine since we almost always close first (I can't fit both on my window!!)

_"Character Type Editor" vs "Character Instance Editor"?_
I think that works

Also, this reveals the issue that the code to generate the instance properties is not using the character type and that is a problem for the wizard. In other words, it says
`prop x setTo 5`
the editor expects
`prop Beaver.x setTo 5`

Is it possible to set the writing code to add the character name in so that the wizard won't complain? It's probably good form anyhow?

**Comment by jdanish** [comment]
Also, since it is so crowded, I am OK removing the model name from the script editor since we currently can only run one model anyhow?

**Comment by jdanish** [comment]
I tried adding a new line of script to change the alpha. When I hit save line, no problem. When I hit save script, no response. I closed the window and the change had taken. Then I tried opening and editing that line, and again no change. I checked the console and this error is there. The changes are saving, but it is choking on the button push.

Screenshot 2023-10-10 at 7 39 57 AM

**Comment by jdanish** [comment]
I also noticed that when I changed alpha, it did not update the character on-screen until I had saved setup. That's fine, but if it is easy to do an update cycle on save, that'd be even better :)

**Comment by benloh** [comment]
> since it is so crowded, I am OK removing the model name from the script editor since we currently can only run one model anyhow?

@jdanish Are you saying you want to remove the character name from panel title bar (e.g. "SCRIPT EDITOR beaver")?  Or were you referring to the character name in the wizard/code view?

**Comment by benloh** [comment]
@jdanish I can't reproduce this error:
> I tried adding a new line of script to change the alpha. When I hit save line, no problem. When I hit save script, no response. I closed the window and the change had taken. Then I tried opening and editing that line, and again no change. I checked the console and this error is there. The changes are saving, but it is choking on the button push.

Screenshot 2023-10-10 at 7 39 57 AM

Please try again after the most recent pushes, which should address some of the update errors.

**Comment by jdanish** [comment]
> @jdanish I can't reproduce this error:
> 
> > I tried adding a new line of script to change the alpha. When I hit save line, no problem. When I hit save script, no response. I closed the window and the change had taken. Then I tried opening and editing that line, and again no change. I checked the console and this error is there. The changes are saving, but it is choking on the button push.
> 
> Screenshot 2023-10-10 at 7 39 57 AM
> Please try again after the most recent pushes, which should address some of the update errors.

Confirmed this is no-longer an issue.

**Comment by jdanish** [comment]
Can you either remove the "delete script" button from the instance editor, or change it to be "delete instance" and change the function accordingly?  I think just removing it might make the most sense?

**Comment by benloh** [comment]
> Can you either remove the "delete script" button from the instance editor, or change it to be "delete instance" and change the function accordingly? I think just removing it might make the most sense?

Removed.  Also removed the "Select Script" button for init script.

**Comment by jdanish** [comment]
Odd one, but ... in the current build, if you do the following:

1. Change a property other than x or y in instance (directly, using external code editor). E.g., adding: prop character.row setTo 2
2. Load script and run - the property is set.
3. Look at instance via setup - the property is set.
4. Load script editor for character type (e.g., NOT the instance)
5. Make some change - doesn't matter what. Save script
6. All instances now only include prop x and prop y - the additional prop character.row setTo 2 has been deleted

**Comment by benloh** [comment]
Sorry, I thought I had fixed that, but obviously I didn't.

**Comment by benloh** [comment]
This should be fixed now.  It was some ancient code that did not account for the fact that we now support using `<bpname>.x` references.

**Comment by benloh** [comment]
@jdanish Ready for more careful review.  Most things should be fixed now.

**Comment by jdanish** [comment]
Looks goos to me. AOK to merge.

**Pull request merged**
